### ISSUE TITLE
[Bug]Redirection does not work as expected

### ISSUE THREAD

**Issue by mohsenkhosroanjam** [daniel-bergmann/german-stories#2]
**Description:**
As a user, I can click on the stories on the left to be redirected to the clicked story.

**Actual result:**
When I click on one story, I am redirected to the story but I should scroll up to see the beginning of the story. 

**Expected result:**
I expect that when I click on one story, I will be redirected to the beginning of that story (the title of the story should be at the top of the webpage).

See the attachment to understand the issue better. 
https://github.com/user-attachments/assets/22fe416f-e169-44e1-97a3-65431aaf10b7

**Comment by daniel-bergmann** [comment]
That's a great observation! Would you like to try to fix it and improve the UI?

**Comment by mohsenkhosroanjam** [comment]
@daniel-bergmann Sure! I am not a software developer but I would love to try fixing it. Will send you a PR as soon as I ensure whether the issue is fixed.

**Comment by daniel-bergmann** [comment]
Fantastic! Good luck and feel free to ask questions!

**Comment by mohsenkhosroanjam** [comment]
@daniel-bergmann Hey, I hope you are doing well. I just sent you a PR. I tested the code with my changes on local and you can see the result in the attachment. I also tested the previous functionalities to ensure my changes did not introduce new bugs. 

https://github.com/user-attachments/assets/9c8740fa-316b-4146-b596-d859a1c9fab5

**Comment by daniel-bergmann** [comment]
bug fixed, well done! :muscle:
